### ISSUE TITLE
Make Russ' results longer and copiable

### ISSUE THREAD

**Issue by ministerinmarin** [lithika-damnod/Russ#8]
**Is your feature request related to a problem? Please describe.**
Russ could make long texts AI results seem missing in context. The app releases up to five lines of text.
![image](https://user-images.githubusercontent.com/104122030/221342717-baaf788b-f1f9-4d79-a640-3019771e0b11.png)
![image](https://user-images.githubusercontent.com/104122030/221342764-c74b0b9d-8346-4e15-a2b1-3601182acba1.png)

**Describe the solution you'd like**
Please make text results longer, especially for analysis, for example poetic analysis or creation of derivative content from the text, at least 2,000 characters, while respecting new lines (\n) if the results return more than one paragraph. At the same time, let the results be copiable to the user's clipboard.

**Describe alternatives you've considered**
Screenshotting the result and OCRing it so text would be copiable

**Additional context**
I bet Russ is in its initial development process, but I find it very interesting. People come to your project and let it analyze the texts they give it and expect results. I look forward to improvements to your project! Sincerely, user from the East.

**Comment by lithika-damnod** [comment]
It's limited to only outputting one paragraph because of the financial problems.. 😔
